language: python

matrix:
  include:
    - env: PYTHON=2.7
    - env: PYTHON=3.6
    - env: PYTHON=3.7

install:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then curl --silent http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh
    -o miniconda.sh; fi
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then wget -nv http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge/label/gcc7
  - conda config --add channels chrisburr
  - conda create -q -n testenv python=${PYTHON} nomkl root pandas nose
  - export CONDA_ENV_PATH=$HOME/miniconda/envs/testenv
  - source activate testenv
  - if [ "${PYTHON}" == "3.7" ]; then
      pip install git+https://github.com/scikit-hep/root_numpy.git;
    else;
      pip install root_numpy;
    fi
  - pip install root_numpy rootpy
  - pip install coverage coveralls

script: nosetests --with-coverage --cover-package=root_pandas

after_success:
  - time coveralls

notifications:
  email: false

deploy:
  provider: pypi
  user: chrisburr
  password:
    secure: MyD2Q4zASzpXWaOBnbkGGm7luYB2SrrBVdX4faN0JmSmDcssn/exu2XDAIwhbZhg3uZC4bq7mBUpPiw/3Mx1f5kFgWlnjpnSRDaGhGLLc6rBp9Kqt6IOWcQ64yQ+S6LIuJ+tjbTMJAlNZgy3HDEwBWXKBvectWKJPZdVCenfMPA=
  on:
    tags: true
    branch: master
